package msg

// Sign-in and sessions.
const (
	NotSignedIn         Code = "auth.notSignedIn"
	AdminOnly           Code = "auth.adminOnly"
	AccountDisabled     Code = "auth.accountDisabled"
	BadCredentials      Code = "auth.badCredentials"
	DomainDenied        Code = "auth.domainDenied"
	GroupDenied         Code = "auth.groupDenied"
	GitHubOrgDenied     Code = "auth.githubOrgDenied"
	ProviderOff         Code = "auth.providerOff"
	ProviderUnavailable Code = "auth.providerUnavailable"
	ProviderSettings    Code = "auth.providerSettings"
	ProviderUnknownType Code = "auth.providerUnknownType"
	ProviderRequired    Code = "auth.providerRequired"
	ProviderRefused     Code = "auth.providerRefused"
	ProviderDecrypt     Code = "auth.providerDecrypt"
	OIDCDiscovery       Code = "auth.oidcDiscovery"
	CodeExchange        Code = "auth.codeExchange"
	NoIDToken           Code = "auth.noIdToken"
	IDTokenInvalid      Code = "auth.idTokenInvalid"
	NonceMismatch       Code = "auth.nonceMismatch"
	GitHubAPI           Code = "auth.githubApi"
	LDAPConnect         Code = "auth.ldapConnect"
	LDAPServiceAccount  Code = "auth.ldapServiceAccount"
	LDAPSearch          Code = "auth.ldapSearch"
	FlowMissing         Code = "auth.flowMissing"
	FlowAltered         Code = "auth.flowAltered"
	FlowExpired         Code = "auth.flowExpired"
	FlowMismatch        Code = "auth.flowMismatch"
	NotRedirect         Code = "auth.notRedirect"
	NotPassword         Code = "auth.notPassword"
	TooManyAttempts     Code = "auth.tooManyAttempts"
	FormExpired         Code = "auth.formExpired"
	TooManyRequests     Code = "auth.tooManyRequests"
	ReturnURLInvalid    Code = "auth.returnUrlInvalid"
	LoginCodeInvalid    Code = "auth.loginCodeInvalid"
)

// API requests.
const (
	NotFound             Code = "api.notFound"
	Internal             Code = "api.internal"
	BadRequest           Code = "api.badRequest"
	BootstrapNoSession   Code = "api.bootstrapNoSession"
	KubeconfigNeedsSSO   Code = "api.kubeconfigNeedsSso"
	ProviderExists       Code = "api.providerExists"
	ProviderIDInvalid    Code = "api.providerIdInvalid"
	ProviderTypeBad      Code = "api.providerTypeInvalid"
	UserPatchInvalid     Code = "api.userPatchInvalid"
	TimeInvalid          Code = "api.timeInvalid"
	APIServerUnreachable Code = "api.apiServerUnreachable"
)

// Bindings and their reconcile status.
const (
	SubjectRequired    Code = "binding.subjectRequired"
	SubjectKindUnknown Code = "binding.subjectKindUnknown"
	SubjectReserved    Code = "binding.subjectReserved"
	SubjectUseGateKind Code = "binding.subjectUseGateKind"
	RoleRequired       Code = "binding.roleRequired"
	RoleInvalid        Code = "binding.roleInvalid"
	NamespacesRequired Code = "binding.namespacesRequired"
	NamespaceInvalid   Code = "binding.namespaceInvalid"
	NamespaceMissing   Code = "binding.namespaceMissing"
	ScopeInvalid       Code = "binding.scopeInvalid"
	ARNInvalid         Code = "binding.arnInvalid"
	AWSAuthMissing     Code = "binding.awsAuthMissing"
	AWSAuthForbidden   Code = "binding.awsAuthForbidden"
	AWSAuthRead        Code = "binding.awsAuthRead"
	AWSAuthInvalid     Code = "binding.awsAuthInvalid"
	AWSAuthUpdate      Code = "binding.awsAuthUpdate"
	RBACListFailed     Code = "binding.rbacListFailed"
)

// Sign-in pages.
const (
	PageTitleSignIn      Code = "page.titleSignIn"
	PageTitleError       Code = "page.titleError"
	PageTitleUnavailable Code = "page.titleUnavailable"
	PageTitleFailed      Code = "page.titleFailed"
	PageTitleTooMany     Code = "page.titleTooMany"
	PageTitleSignedIn    Code = "page.titleSignedIn"
	PageSignInIntro      Code = "page.signInIntro"
	PageNoProviders      Code = "page.noProviders"
	PageUsername         Code = "page.username"
	PagePassword         Code = "page.password"
	PageSignInWith       Code = "page.signInWith"
	PageContinueWith     Code = "page.continueWith"
	PageErrorHeading     Code = "page.errorHeading"
	PageBack             Code = "page.back"
	PageSignedInHeading  Code = "page.signedInHeading"
	PageSignedInAs       Code = "page.signedInAs"
	PageAccessUntil      Code = "page.accessUntil"
	PageDownload         Code = "page.download"
	PageShowKubeconfig   Code = "page.showKubeconfig"
	PageKubeconfigHint   Code = "page.kubeconfigHint"
	PageReturnToApp      Code = "page.returnToApp"
	PageAppRequest       Code = "page.appRequest"
)
