package msg

var en = map[Code]string{
	NotSignedIn:         "Sign in to Roam Gate first: the token is missing, expired or revoked.",
	AdminOnly:           "Only Roam Gate admins can do this.",
	AccountDisabled:     "This account is disabled in Roam Gate.",
	BadCredentials:      "Wrong username or password.",
	DomainDenied:        "Your email domain is not allowed to sign in.",
	GroupDenied:         "You are not in a group that is allowed to sign in.",
	GitHubOrgDenied:     "You are not a member of an organization that may sign in (check the app's organization access on GitHub).",
	ProviderOff:         "This sign-in method is turned off.",
	ProviderUnavailable: "This sign-in method is not available: {error}",
	ProviderSettings:    "The settings of sign-in method {id} are invalid: {error}",
	ProviderUnknownType: "Unknown sign-in method type {type}.",
	ProviderRequired:    "These settings are required: {fields}.",
	ProviderRefused:     "The sign-in provider refused: {error}",
	ProviderDecrypt:     "The settings of sign-in method {id} can't be decrypted (was GATE_SECRET_KEY changed?).",
	OIDCDiscovery:       "Couldn't reach the OpenID Connect provider at {issuer}: {error}",
	CodeExchange:        "Couldn't finish signing in with the provider: {error}",
	NoIDToken:           "The provider returned no ID token.",
	IDTokenInvalid:      "The provider's ID token is not valid: {error}",
	NonceMismatch:       "The sign-in response doesn't belong to this sign-in; start again.",
	GitHubAPI:           "GitHub {path}: {status}",
	LDAPConnect:         "Couldn't connect to LDAP: {error}",
	LDAPServiceAccount:  "The LDAP service account was rejected: {error}",
	LDAPSearch:          "The LDAP search failed: {error}",
	FlowMissing:         "The sign-in expired or was started in another browser; start again.",
	FlowAltered:         "The sign-in state was altered.",
	FlowExpired:         "The sign-in took too long; start again.",
	FlowMismatch:        "The sign-in state doesn't match; start again.",
	NotRedirect:         "This sign-in method doesn't use a browser redirect.",
	NotPassword:         "This sign-in method doesn't use a password.",
	TooManyAttempts:     "Too many sign-in attempts; wait a minute and try again.",
	FormExpired:         "The form expired; go back and try again.",
	TooManyRequests:     "Too many sign-in requests; try again in a minute.",
	ReturnURLInvalid:    "The app's return address must be http://127.0.0.1:<port> or http://localhost:<port>.",
	LoginCodeInvalid:    "The sign-in code is wrong or was already used.",

	NotFound:             "Not found.",
	Internal:             "Something went wrong: {error}",
	BadRequest:           "The request is not valid: {error}",
	BootstrapNoSession:   "The bootstrap admin token has no session.",
	KubeconfigNeedsSSO:   "Sign in with SSO to get a kubeconfig.",
	ProviderExists:       "A sign-in method with ID {id} already exists.",
	ProviderIDInvalid:    "The ID must be lowercase letters, digits and dashes, up to 40 characters (it becomes part of group names).",
	ProviderTypeBad:      "The type must be one of {types}.",
	UserPatchInvalid:     `Send {"disabled": true} or {"disabled": false}.`,
	APIServerUnreachable: "Gate could not reach the Kubernetes API server.",
	TimeInvalid:          "{field}: use RFC 3339, e.g. 2026-10-01T00:00:00Z.",

	SubjectRequired:    "Say who gets access.",
	SubjectKindUnknown: "Unknown kind of subject {kind}.",
	SubjectReserved:    "{subject} can't be granted access through Gate: it would cover {who}.",
	SubjectUseGateKind: "{subject} is a Gate name; grant it as a Gate person or team instead.",
	RoleRequired:       "Pick a role.",
	RoleInvalid:        "{role} is not a valid role name.",
	NamespacesRequired: "Pick at least one namespace, or grant it on the whole cluster.",
	NamespaceInvalid:   "{namespace} is not a valid namespace name.",
	NamespaceMissing:   "Namespace {namespace} doesn't exist.",
	ScopeInvalid:       "The scope must be cluster or namespaces.",
	ARNInvalid:         "Expected an IAM role or user ARN, like arn:aws:iam::123456789012:role/Developers.",
	AWSAuthMissing:     "This cluster has no aws-auth ConfigMap (not EKS, or it uses access entries only — add the access entry from Roam).",
	AWSAuthForbidden:   "Gate may not edit aws-auth: install the chart with eks.awsAuth=true.",
	AWSAuthRead:        "Couldn't read aws-auth: {error}",
	AWSAuthInvalid:     "aws-auth is not valid YAML, so Gate leaves it alone: {error}",
	AWSAuthUpdate:      "Couldn't update aws-auth: {error}",
	RBACListFailed:     "Couldn't list {what}: {error}",

	PageTitleSignIn:      "Sign in",
	PageTitleError:       "Roam Gate",
	PageTitleUnavailable: "Sign-in unavailable",
	PageTitleFailed:      "Sign-in failed",
	PageTitleTooMany:     "Too many attempts",
	PageTitleSignedIn:    "Signed in",
	PageSignInIntro:      "Use your organization account to get access to this cluster.",
	PageNoProviders:      "No sign-in method is set up yet. Ask your administrator to add one in Roam.",
	PageUsername:         "{provider} username",
	PagePassword:         "Password",
	PageSignInWith:       "Sign in with {provider}",
	PageContinueWith:     "Continue with {provider}",
	PageErrorHeading:     "Something went wrong",
	PageBack:             "Back to sign-in",
	PageSignedInHeading:  "You're signed in",
	PageSignedInAs:       "Signed in as {user}.",
	PageAccessUntil:      "Your access lasts until {expires}.",
	PageDownload:         "Download kubeconfig",
	PageShowKubeconfig:   "Show kubeconfig",
	PageKubeconfigHint:   "Use it with kubectl --kubeconfig kubeconfig-roam-gate.yaml get pods, or open this cluster in Roam. Keep the file private: it works as your password until it expires.",
	PageReturnToApp:      "Going back to Roam…",
	PageAppRequest:       "Roam on this computer asked to sign you in.",
}
