package msg

var vi = map[Code]string{
	NotSignedIn:         "Hãy đăng nhập Roam Gate trước: token bị thiếu, đã hết hạn hoặc đã bị thu hồi.",
	AdminOnly:           "Chỉ quản trị viên Roam Gate mới làm được việc này.",
	AccountDisabled:     "Tài khoản này đã bị vô hiệu hoá trong Roam Gate.",
	BadCredentials:      "Sai tên đăng nhập hoặc mật khẩu.",
	DomainDenied:        "Tên miền email của bạn không được phép đăng nhập.",
	GroupDenied:         "Bạn không thuộc nhóm nào được phép đăng nhập.",
	GitHubOrgDenied:     "Bạn không thuộc tổ chức nào được phép đăng nhập (kiểm tra quyền truy cập tổ chức của app trên GitHub).",
	ProviderOff:         "Phương thức đăng nhập này đang tắt.",
	ProviderUnavailable: "Phương thức đăng nhập này không dùng được: {error}",
	ProviderSettings:    "Cấu hình của phương thức đăng nhập {id} không hợp lệ: {error}",
	ProviderUnknownType: "Không rõ loại phương thức đăng nhập {type}.",
	ProviderRequired:    "Cần điền các cấu hình: {fields}.",
	ProviderRefused:     "Nhà cung cấp đăng nhập từ chối: {error}",
	ProviderDecrypt:     "Không giải mã được cấu hình của phương thức đăng nhập {id} (GATE_SECRET_KEY có bị đổi không?).",
	OIDCDiscovery:       "Không kết nối được nhà cung cấp OpenID Connect tại {issuer}: {error}",
	CodeExchange:        "Không hoàn tất được việc đăng nhập với nhà cung cấp: {error}",
	NoIDToken:           "Nhà cung cấp không trả về ID token.",
	IDTokenInvalid:      "ID token của nhà cung cấp không hợp lệ: {error}",
	NonceMismatch:       "Phản hồi đăng nhập không thuộc lần đăng nhập này; hãy bắt đầu lại.",
	GitHubAPI:           "GitHub {path}: {status}",
	LDAPConnect:         "Không kết nối được LDAP: {error}",
	LDAPServiceAccount:  "Tài khoản dịch vụ LDAP bị từ chối: {error}",
	LDAPSearch:          "Tìm kiếm LDAP thất bại: {error}",
	FlowMissing:         "Phiên đăng nhập đã hết hạn hoặc được bắt đầu ở trình duyệt khác; hãy bắt đầu lại.",
	FlowAltered:         "Trạng thái đăng nhập đã bị sửa đổi.",
	FlowExpired:         "Đăng nhập quá lâu; hãy bắt đầu lại.",
	FlowMismatch:        "Trạng thái đăng nhập không khớp; hãy bắt đầu lại.",
	NotRedirect:         "Phương thức đăng nhập này không chuyển hướng qua trình duyệt.",
	NotPassword:         "Phương thức đăng nhập này không dùng mật khẩu.",
	TooManyAttempts:     "Đăng nhập sai quá nhiều lần; đợi một phút rồi thử lại.",
	FormExpired:         "Biểu mẫu đã hết hạn; quay lại và thử lại.",
	TooManyRequests:     "Quá nhiều yêu cầu đăng nhập; thử lại sau một phút.",
	ReturnURLInvalid:    "Địa chỉ quay về của app phải là http://127.0.0.1:<cổng> hoặc http://localhost:<cổng>.",
	LoginCodeInvalid:    "Mã đăng nhập sai hoặc đã được dùng.",

	NotFound:             "Không tìm thấy.",
	Internal:             "Đã có lỗi: {error}",
	BadRequest:           "Yêu cầu không hợp lệ: {error}",
	BootstrapNoSession:   "Token admin khởi tạo không có phiên đăng nhập.",
	KubeconfigNeedsSSO:   "Hãy đăng nhập bằng SSO để lấy kubeconfig.",
	ProviderExists:       "Đã có phương thức đăng nhập với ID {id}.",
	ProviderIDInvalid:    "ID chỉ gồm chữ thường, số và dấu gạch ngang, tối đa 40 ký tự (nó là một phần của tên nhóm).",
	ProviderTypeBad:      "Loại phải là một trong {types}.",
	UserPatchInvalid:     `Gửi {"disabled": true} hoặc {"disabled": false}.`,
	APIServerUnreachable: "Gate không kết nối được Kubernetes API server.",
	TimeInvalid:          "{field}: dùng định dạng RFC 3339, ví dụ 2026-10-01T00:00:00Z.",

	SubjectRequired:    "Hãy chọn người được cấp quyền.",
	SubjectKindUnknown: "Không rõ loại đối tượng {kind}.",
	SubjectReserved:    "Không thể cấp quyền cho {subject} qua Gate: nó bao gồm {who}.",
	SubjectUseGateKind: "{subject} là tên trong Gate; hãy cấp quyền theo người hoặc nhóm của Gate.",
	RoleRequired:       "Hãy chọn một role.",
	RoleInvalid:        "{role} không phải tên role hợp lệ.",
	NamespacesRequired: "Chọn ít nhất một namespace, hoặc cấp quyền trên toàn cluster.",
	NamespaceInvalid:   "{namespace} không phải tên namespace hợp lệ.",
	NamespaceMissing:   "Namespace {namespace} không tồn tại.",
	ScopeInvalid:       "Phạm vi phải là cluster hoặc namespaces.",
	ARNInvalid:         "Cần một ARN của IAM role hoặc user, ví dụ arn:aws:iam::123456789012:role/Developers.",
	AWSAuthMissing:     "Cluster này không có ConfigMap aws-auth (không phải EKS, hoặc chỉ dùng access entry — hãy thêm access entry từ Roam).",
	AWSAuthForbidden:   "Gate không được sửa aws-auth: hãy cài chart với eks.awsAuth=true.",
	AWSAuthRead:        "Không đọc được aws-auth: {error}",
	AWSAuthInvalid:     "aws-auth không phải YAML hợp lệ nên Gate không động vào: {error}",
	AWSAuthUpdate:      "Không cập nhật được aws-auth: {error}",
	RBACListFailed:     "Không liệt kê được {what}: {error}",

	PageTitleSignIn:      "Đăng nhập",
	PageTitleError:       "Roam Gate",
	PageTitleUnavailable: "Không đăng nhập được",
	PageTitleFailed:      "Đăng nhập thất bại",
	PageTitleTooMany:     "Thử quá nhiều lần",
	PageTitleSignedIn:    "Đã đăng nhập",
	PageSignInIntro:      "Dùng tài khoản tổ chức của bạn để truy cập cluster này.",
	PageNoProviders:      "Chưa có phương thức đăng nhập nào. Hãy nhờ quản trị viên thêm trong Roam.",
	PageUsername:         "Tên đăng nhập {provider}",
	PagePassword:         "Mật khẩu",
	PageSignInWith:       "Đăng nhập bằng {provider}",
	PageContinueWith:     "Tiếp tục với {provider}",
	PageErrorHeading:     "Đã có lỗi",
	PageBack:             "Quay lại trang đăng nhập",
	PageSignedInHeading:  "Bạn đã đăng nhập",
	PageSignedInAs:       "Đã đăng nhập với {user}.",
	PageAccessUntil:      "Quyền truy cập của bạn có hiệu lực đến {expires}.",
	PageDownload:         "Tải kubeconfig",
	PageShowKubeconfig:   "Xem kubeconfig",
	PageKubeconfigHint:   "Dùng với kubectl --kubeconfig kubeconfig-roam-gate.yaml get pods, hoặc mở cluster này trong Roam. Giữ file này bí mật: nó có tác dụng như mật khẩu cho đến khi hết hạn.",
	PageReturnToApp:      "Đang quay lại Roam…",
	PageAppRequest:       "Roam trên máy này đã yêu cầu đăng nhập cho bạn.",
}
